// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, RequestCapability, RuntimeFailure};

pub const CAPABILITY_ID: &str = "lenso.web.shell@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const SHELL_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const SHELL_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

pub const READ_ASSET_OPERATION: &str = "read_asset";
pub const RENDER_ROUTE_OPERATION: &str = "render_route";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadAssetRequest {
    #[serde(rename = "path")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub path: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadAssetResponse {
    #[serde(rename = "content")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content: String,
    #[serde(rename = "content_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_type: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadAssetError {
    AssetNotFound,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenderRouteRequest {
    #[serde(rename = "path")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub path: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenderRouteResponse {
    #[serde(rename = "asset_paths")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub asset_paths: Vec<String>,
    #[serde(rename = "body")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body: String,
    #[serde(rename = "contribution_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub contribution_id: String,
    #[serde(rename = "navigation")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub navigation: Vec<RenderRouteResponseNavigationItem>,
    #[serde(rename = "requirements")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requirements: Vec<RenderRouteResponseRequirementsItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenderRouteResponseNavigationItem {
    #[serde(rename = "label")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub label: String,
    #[serde(rename = "route")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub route: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenderRouteResponseRequirementsItem {
    #[serde(rename = "capability_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub capability_id: String,
    #[serde(rename = "descriptor_version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub descriptor_version: String,
    #[serde(rename = "operations")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operations: Vec<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RenderRouteError {
    RouteNotFound,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ShellReadAsset;
impl RequestCapability for ShellReadAsset {
    type Request = ReadAssetRequest;
    type Response = ReadAssetResponse;
    type DomainError = ReadAssetError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_ASSET_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ShellRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_asset(context, request)
    }
}

#[derive(Debug)]
pub struct ShellRenderRoute;
impl RequestCapability for ShellRenderRoute {
    type Request = RenderRouteRequest;
    type Response = RenderRouteResponse;
    type DomainError = RenderRouteError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RENDER_ROUTE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ShellRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).render_route(context, request)
    }
}

impl serde::Serialize for ReadAssetError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AssetNotFound => serializer.serialize_str("asset_not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadAssetError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "asset_not_found" => Ok(Self::AssetNotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RenderRouteError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::RouteNotFound => serializer.serialize_str("route_not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RenderRouteError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "route_not_found" => Ok(Self::RouteNotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_read_asset_request(value: &ReadAssetRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_asset_request(wire: &str) -> Result<ReadAssetRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_asset_response(value: &ReadAssetResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_asset_response(wire: &str) -> Result<ReadAssetResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_asset_error(value: &ReadAssetError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_asset_error(wire: &str) -> Result<ReadAssetError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_render_route_request(value: &RenderRouteRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_render_route_request(wire: &str) -> Result<RenderRouteRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_render_route_response(value: &RenderRouteResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_render_route_response(wire: &str) -> Result<RenderRouteResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_render_route_error(value: &RenderRouteError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_render_route_error(wire: &str) -> Result<RenderRouteError, serde_json::Error> { decode_portable_json(wire) }

pub trait ShellProvider: fmt::Debug + 'static {
    fn read_asset(&self, context: InvocationContext, request: ReadAssetRequest) -> NativeRequestFuture<ShellReadAsset>;
    fn render_route(&self, context: InvocationContext, request: RenderRouteRequest) -> NativeRequestFuture<ShellRenderRoute>;
}

#[derive(Debug)]
struct ShellRequestEndpoint { provider: Rc<dyn ShellProvider> }

#[derive(Debug)]
pub struct ShellEndpoint<P: ShellProvider> { provider: Rc<P>, request_endpoint: ShellRequestEndpoint }
impl<P: ShellProvider> ShellEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ShellProvider> = provider.clone();
        Self { provider, request_endpoint: ShellRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ShellProvider> NativeRequestEndpoint for ShellEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        READ_ASSET_OPERATION,
        RENDER_ROUTE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            READ_ASSET_OPERATION => {
                let Ok(request) = request.downcast::<ReadAssetRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_asset(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RENDER_ROUTE_OPERATION => {
                let Ok(request) = request.downcast::<RenderRouteRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).render_route(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[derive(Debug)]
pub struct ShellClient {
    read_asset: NativeRequestHandle<ShellReadAsset>,
    render_route: NativeRequestHandle<ShellRenderRoute>,
}
impl ShellClient {
    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            read_asset: dependencies.one::<ShellReadAsset>()?,
            render_route: dependencies.one::<ShellRenderRoute>()?,
        })
    }

    pub async fn read_asset(&self, request: ReadAssetRequest) -> Result<ReadAssetResponse, ShellReadAssetInvocationError> {
        self.read_asset.invoke(READ_ASSET_OPERATION, request).await
            .map_err(ShellReadAssetInvocationError::Runtime)?
            .map_err(ShellReadAssetInvocationError::Domain)
    }

    pub async fn read_asset_with_context(&self, context: InvocationContext, request: ReadAssetRequest) -> Result<ReadAssetResponse, ShellReadAssetInvocationError> {
        self.read_asset.invoke_with_context(READ_ASSET_OPERATION, context, request).await
            .map_err(ShellReadAssetInvocationError::Runtime)?
            .map_err(ShellReadAssetInvocationError::Domain)
    }

    pub async fn render_route(&self, request: RenderRouteRequest) -> Result<RenderRouteResponse, ShellRenderRouteInvocationError> {
        self.render_route.invoke(RENDER_ROUTE_OPERATION, request).await
            .map_err(ShellRenderRouteInvocationError::Runtime)?
            .map_err(ShellRenderRouteInvocationError::Domain)
    }

    pub async fn render_route_with_context(&self, context: InvocationContext, request: RenderRouteRequest) -> Result<RenderRouteResponse, ShellRenderRouteInvocationError> {
        self.render_route.invoke_with_context(RENDER_ROUTE_OPERATION, context, request).await
            .map_err(ShellRenderRouteInvocationError::Runtime)?
            .map_err(ShellRenderRouteInvocationError::Domain)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShellReadAssetInvocationError {
    Domain(ReadAssetError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ShellRenderRouteInvocationError {
    Domain(RenderRouteError),
    Runtime(RuntimeFailure),
}
